/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.AutocombustionJpaController;
import Controlador.TerrestreJpaController;
import Controlador.VehiculoJpaController;
import Controlador.exceptions.NonexistentEntityException;
import Controlador.exceptions.PreexistingEntityException;
import Modelo.Autocombustion;
import Modelo.Terrestre;
import Modelo.Vehiculo;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author es982
 */
public class AutoCombustion extends javax.swing.JFrame {

    /**
     * Creates new form AutoCombustion
     */
    private AutocombustionJpaController controlAutoCombustion= new AutocombustionJpaController();
    private VehiculoJpaController controlVehiculo =new VehiculoJpaController();
    private TerrestreJpaController controlTerrestre=new TerrestreJpaController();
    private Autocombustion autoC =new Autocombustion();
    private Terrestre terr=new Terrestre();
    private Vehiculo veh1= new Vehiculo();
    private Integer idA=0;
    
    public AutoCombustion() {
        initComponents();
        cargarTablaAuto();
    }
    
    //Metodos de logica
    private void cargarTablaAuto() {
        DefaultTableModel modelo = (DefaultTableModel) tb_autoComb.getModel();
        modelo.setRowCount(0);
        try {
            List<Autocombustion> lista = controlAutoCombustion.findAutocombustionEntities();
            for (Autocombustion aC : lista) {
                Terrestre t = aC.getTerrestre();
                Vehiculo v= t.getVehiculo();
                String estatus;
                if(v.getReservado())estatus="Si";
                else estatus="No";
                if (t != null && v !=null) {
                    modelo.addRow(new Object[]{
                        v.getIdVehiculo(), v.getMarca(), v.getModelo(), v.getPrecio(), v.getAño(), estatus, t.getNoPuertas(), t.getTipoCombustible()
                    });
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar docentes. Intenta nuevamente.");
        }
    }
    private void limpiarCampos() {
    txtMarca.setText("");
    txtModelo.setText("");
    txtPrecio.setText("");
    txtAño.setText("");
    txtnPuertas.setText("");
    txtTipoCombustible.setText("");
    cboReservado.setSelectedIndex(0);
    this.idA = 0; // Resetea el ID seleccionado
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTipoCombustible = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboReservado = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtnPuertas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        scrollAutoC = new javax.swing.JScrollPane();
        tb_autoComb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Auto de Combustible");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 260, 34));

        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Marca:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        panel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Modelo:");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        panel1.add(txtTipoCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("N° Puertas:");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));
        panel1.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Reservado:");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        cboReservado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboReservado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        panel1.add(cboReservado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        panel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Buscar:");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel7.setText("Lupa");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 40, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Año:");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));
        panel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 110, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Precio:");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));
        panel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 30));
        panel1.add(txtnPuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Tipo de Combustible:");
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 750, 210));

        panel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_autoComb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_Vehiculo", "Marca", "Modelo", "Precio", "Año", "Reservado", "N° Puertas", "Tipo_Combustible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_autoComb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_autoCombMouseClicked(evt);
            }
        });
        scrollAutoC.setViewportView(tb_autoComb);

        panel2.add(scrollAutoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 240));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 750, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // 1. VALIDACIÓN DE CAMPOS VACÍOS
    if (txtMarca.getText().isEmpty() || txtModelo.getText().isEmpty() || 
        txtPrecio.getText().isEmpty() || txtAño.getText().isEmpty() || 
        txtnPuertas.getText().isEmpty() || txtTipoCombustible.getText().isEmpty()) {
        
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // 2. CREACIÓN DE OBJETOS LOCALES (NO USAR LOS DE LA CLASE)
        Vehiculo vehiculoNuevo = new Vehiculo();
        Terrestre terrestreNuevo = new Terrestre();
        Autocombustion autoCNuevo = new Autocombustion();

        // 3. OBTENCIÓN Y ASIGNACIÓN DE DATOS AL VEHÍCULO
        vehiculoNuevo.setMarca(txtMarca.getText());
        vehiculoNuevo.setModelo(txtModelo.getText());
        vehiculoNuevo.setPrecio(new BigDecimal(txtPrecio.getText()));
        vehiculoNuevo.setAño(Integer.parseInt(txtAño.getText()));
        vehiculoNuevo.setReservado("Si".equals(cboReservado.getSelectedItem().toString()));
        
        // 4. ASIGNACIÓN DE DATOS AL TERRESTRE Y ENLACE CON VEHÍCULO
        terrestreNuevo.setNoPuertas(Integer.parseInt(txtnPuertas.getText()));
        terrestreNuevo.setTipoCombustible(txtTipoCombustible.getText());
        terrestreNuevo.setVehiculo(vehiculoNuevo); // Enlace clave
        
        // 5. ENLACE DE AUTOCOMBUSTION CON TERRESTRE
        autoCNuevo.setTerrestre(terrestreNuevo); // Enlace clave

        // 6. PERSISTENCIA EN LA BASE DE DATOS
        // JPA se encarga de asignar los IDs correctamente gracias a los enlaces
        controlVehiculo.create(vehiculoNuevo);
        terrestreNuevo.setIdVehiculo(vehiculoNuevo.getIdVehiculo()); // Asignamos el ID generado
        controlTerrestre.create(terrestreNuevo);
        autoCNuevo.setIdVehiculo(vehiculoNuevo.getIdVehiculo()); // Asignamos el ID generado
        controlAutoCombustion.create(autoCNuevo);

        JOptionPane.showMessageDialog(this, "Vehículo guardado exitosamente.", "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: El precio, año y número de puertas deben ser números válidos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar el vehículo: " + e.getMessage(), "Error General", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(AutoCombustion.class.getName()).log(Level.SEVERE, null, e);
    } finally {
        // 7. ACTUALIZAR TABLA Y LIMPIAR CAMPOS
        cargarTablaAuto();
        limpiarCampos();
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tb_autoCombMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_autoCombMouseClicked
         int fila = tb_autoComb.getSelectedRow();
            if (fila != -1) { // si hay fila seleccionada
                idA=Integer.parseInt(tb_autoComb.getValueAt(fila,0).toString());
                // Recupera los valores de la tabla
                //String placa = tb_autoComb.getValueAt(fila, 0).toString();
                String marca = tb_autoComb.getValueAt(fila, 1).toString();
                String modelo = tb_autoComb.getValueAt(fila, 2).toString();
                String precio = tb_autoComb.getValueAt(fila, 3).toString();
                String año = tb_autoComb.getValueAt(fila, 4).toString();
                String reservado = tb_autoComb.getValueAt(fila, 5).toString();
                String num_puertas = tb_autoComb.getValueAt(fila, 6).toString();
                String tipoCombustible = tb_autoComb.getValueAt(fila, 7).toString();
                

                // Rellena los JTextField
                txtModelo.setText(modelo);
                txtMarca.setText(marca);
                txtTipoCombustible.setText(tipoCombustible);
                txtAño.setText(año);
                txtPrecio.setText(precio);
                cboReservado.setSelectedItem(reservado);
                //txtReservado.setText(precio);
                txtnPuertas.setText(num_puertas);
            }
    }//GEN-LAST:event_tb_autoCombMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // 1. VALIDACIÓN DE SELECCIÓN
    if (this.idA == null || this.idA == 0) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un vehículo de la tabla para modificar.", "Error de Selección", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 2. VALIDACIÓN DE CAMPOS VACÍOS
    if (txtMarca.getText().isEmpty() || txtModelo.getText().isEmpty() || 
        txtPrecio.getText().isEmpty() || txtAño.getText().isEmpty() || 
        txtnPuertas.getText().isEmpty() || txtTipoCombustible.getText().isEmpty()) {
        
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // 3. OBTENER LOS OBJETOS EXISTENTES DE LA BD
        Autocombustion autoAModificar = controlAutoCombustion.findAutocombustion(idA);
        if (autoAModificar == null) {
            JOptionPane.showMessageDialog(this, "El vehículo seleccionado ya no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Terrestre terrestreAModificar = autoAModificar.getTerrestre();
        Vehiculo vehiculoAModificar = terrestreAModificar.getVehiculo();

        // 4. ACTUALIZAR PROPIEDADES DE LOS OBJETOS EXISTENTES
        vehiculoAModificar.setMarca(txtMarca.getText());
        vehiculoAModificar.setModelo(txtModelo.getText());
        vehiculoAModificar.setPrecio(new BigDecimal(txtPrecio.getText()));
        vehiculoAModificar.setAño(Integer.parseInt(txtAño.getText()));
        vehiculoAModificar.setReservado("Si".equals(cboReservado.getSelectedItem().toString()));
        
        terrestreAModificar.setNoPuertas(Integer.parseInt(txtnPuertas.getText()));
        terrestreAModificar.setTipoCombustible(txtTipoCombustible.getText());

        // El objeto autoAModificar no tiene campos propios en este formulario, así que no se actualiza directamente.

        // 5. GUARDAR LOS CAMBIOS EN LA BASE DE DATOS
        controlVehiculo.edit(vehiculoAModificar);
        controlTerrestre.edit(terrestreAModificar);
        // No es necesario llamar a controlAutoCombustion.edit() si no cambian sus propios campos.

        JOptionPane.showMessageDialog(this, "Vehículo modificado exitosamente.", "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: El precio, año y número de puertas deben ser números válidos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al modificar el vehículo: " + e.getMessage(), "Error General", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(AutoCombustion.class.getName()).log(Level.SEVERE, null, e);
    } finally {
        // 6. ACTUALIZAR TABLA Y LIMPIAR CAMPOS
        cargarTablaAuto();
        limpiarCampos();
    }
    }//GEN-LAST:event_btnModificarActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoCombustion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoCombustion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoCombustion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoCombustion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoCombustion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboReservado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JScrollPane scrollAutoC;
    private javax.swing.JTable tb_autoComb;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTipoCombustible;
    private javax.swing.JTextField txtnPuertas;
    // End of variables declaration//GEN-END:variables
}
