/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Renta;
import Modelo.Cliente;
import Modelo.Vehiculo;
import Controlador.RentaJpaController;
import Controlador.ClienteJpaController;
import Controlador.VehiculoJpaController;
import java.util.List;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author es982
 */
public class GestionRentas extends javax.swing.JFrame {

    private RentaJpaController controlRenta;
    private ClienteJpaController controlCliente;
    private VehiculoJpaController controlVehiculo;

    /**
     * Creates new form GestionRentas
     */
    public GestionRentas() {
        try {
            controlRenta = new RentaJpaController();
            controlCliente = new ClienteJpaController();
            controlVehiculo = new VehiculoJpaController();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos: " + e.getMessage());
            e.printStackTrace();
            return;
        }
        initComponents();
        cargarTabla();
        cargarClientes();
        cargarVehiculos();
    }

    private void cargarTabla() {
        if (controlRenta == null) return;
        DefaultTableModel modelo = (DefaultTableModel) tbRentas.getModel();
        modelo.setRowCount(0);
        try {
            List<Renta> lista = controlRenta.findRentaEntities();
            for (Renta r : lista) {
                Object[] fila = {
                    r.getIdRenta(),
                    r.getIdCliente().getNombre(),
                    r.getIdVehiculo().getMarca() + " " + r.getIdVehiculo().getModelo(),
                    r.getFechaInicio(),
                    r.getFechaFin(),
                    r.getTarifaDiaria(),
                    r.getEstado()
                };
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar rentas: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void cargarClientes() {
        if (controlCliente == null) return;
        cbCliente.removeAllItems();
        try {
            List<Cliente> lista = controlCliente.findClienteEntities();
            for (Cliente c : lista) {
                cbCliente.addItem(c.getIdCliente() + " - " + c.getNombre());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar clientes: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void cargarVehiculos() {
        if (controlVehiculo == null) return;
        cbVehiculo.removeAllItems();
        try {
            List<Vehiculo> lista = controlVehiculo.findVehiculoEntities();
            for (Vehiculo v : lista) {
                cbVehiculo.addItem(v.getIdVehiculo() + " - " + v.getMarca() + " " + v.getModelo());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar vehículos: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRentas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbVehiculo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 58, 128));
        jLabel1.setText("📋 Gestión de Rentas");
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tbRentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Vehículo", "Fecha Inicio", "Fecha Fin", "Tarifa", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRentas.setBackground(new java.awt.Color(248, 249, 250));
        tbRentas.setFont(new java.awt.Font("Segoe UI", 0, 12));
        tbRentas.setGridColor(new java.awt.Color(220, 220, 220));
        tbRentas.setRowHeight(25);
        tbRentas.setSelectionBackground(new java.awt.Color(76, 175, 80));
        tbRentas.setSelectionForeground(java.awt.Color.WHITE);
        tbRentas.getTableHeader().setBackground(new java.awt.Color(30, 58, 128));
        tbRentas.getTableHeader().setForeground(java.awt.Color.WHITE);
        tbRentas.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 12));
        jScrollPane1.setViewportView(tbRentas);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel2.setForeground(new java.awt.Color(60, 60, 60));
        jLabel2.setText("Cliente:");

        cbCliente.setFont(new java.awt.Font("Segoe UI", 0, 12));
        cbCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel3.setForeground(new java.awt.Color(60, 60, 60));
        jLabel3.setText("Vehiculo:");

        cbVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 12));
        cbVehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel4.setForeground(new java.awt.Color(60, 60, 60));
        jLabel4.setText("Fecha Inicio (YYYY-MM-DD):");

        txtFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 12));
        txtFechaInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel5.setForeground(new java.awt.Color(60, 60, 60));
        jLabel5.setText("Fecha Fin (YYYY-MM-DD):");

        txtFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 12));
        txtFechaFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12));
        jLabel6.setForeground(new java.awt.Color(60, 60, 60));
        jLabel6.setText("Tarifa Diaria:");

        txtTarifa.setFont(new java.awt.Font("Segoe UI", 0, 12));
        txtTarifa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));

        btnCrear.setBackground(new java.awt.Color(76, 175, 80));
        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 14));
        btnCrear.setForeground(java.awt.Color.WHITE);
        btnCrear.setText("CREAR RENTA");
        btnCrear.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
        btnCrear.setBorderPainted(false);
        btnCrear.setFocusPainted(false);
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.setOpaque(true);
        btnCrear.setPreferredSize(new java.awt.Dimension(140, 40));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnRefrescar.setBackground(new java.awt.Color(33, 150, 243));
        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 1, 14));
        btnRefrescar.setForeground(java.awt.Color.WHITE);
        btnRefrescar.setText("REFRESCAR");
        btnRefrescar.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));
        btnRefrescar.setBorderPainted(false);
        btnRefrescar.setFocusPainted(false);
        btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefrescar.setOpaque(true);
        btnRefrescar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnCrear)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btnRefrescar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear)
                    .addComponent(btnRefrescar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
            String clienteStr = (String) cbCliente.getSelectedItem();
            String vehiculoStr = (String) cbVehiculo.getSelectedItem();
            String fechaInicioStr = txtFechaInicio.getText();
            String fechaFinStr = txtFechaFin.getText();
            String tarifaStr = txtTarifa.getText();

            if (clienteStr == null || vehiculoStr == null || fechaInicioStr.isEmpty() || fechaFinStr.isEmpty() || tarifaStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Complete todos los campos.");
                return;
            }

            int idCliente = Integer.parseInt(clienteStr.split(" - ")[0]);
            int idVehiculo = Integer.parseInt(vehiculoStr.split(" - ")[0]);
            java.sql.Date fechaInicio = java.sql.Date.valueOf(fechaInicioStr);
            java.sql.Date fechaFin = java.sql.Date.valueOf(fechaFinStr);
            BigDecimal tarifa = new BigDecimal(tarifaStr);

            Cliente cliente = controlCliente.findCliente(idCliente);
            Vehiculo vehiculo = controlVehiculo.findVehiculo(idVehiculo);

            Renta renta = new Renta();
            renta.setIdCliente(cliente);
            renta.setIdVehiculo(vehiculo);
            renta.setFechaInicio(fechaInicio);
            renta.setFechaFin(fechaFin);
            renta.setTarifaDiaria(tarifa);
            renta.setEstado("Activa");

            controlRenta.create(renta);
            JOptionPane.showMessageDialog(this, "Renta creada exitosamente.");
            cargarTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear renta: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionRentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionRentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionRentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionRentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionRentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbRentas;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtTarifa;
    // End of variables declaration//GEN-END:variables
}