/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.UsuarioJpaController;
import Modelo.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/**
 *
 * @author jc389
 */
public class IniciarSesion extends javax.swing.JFrame {

    public String textUser = "Ingrese su usuario o correo electrónico:";
    public String textPass = "Ingrese su contraseña:";

    String codigo = "";
    //String codigo = email.getCodigo();
    int contador;


    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {

        initComponents();
        lblVer1.setVisible(false);
        this.setLocationRelativeTo(null);
        ajustar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        iniciaSesion = new javax.swing.JLabel();
        frase_derecha = new javax.swing.JLabel();
        frase1 = new javax.swing.JLabel();
        bienvenido = new javax.swing.JLabel();
        SIGERPRO = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        fondoOscuro = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblVer1 = new javax.swing.JLabel();
        lblVer = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblRecuperar = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        fondoClaro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(687, 410));
        setPreferredSize(new java.awt.Dimension(879, 543));
        setSize(new java.awt.Dimension(879, 543));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelInicio.setPreferredSize(new java.awt.Dimension(1009, 539));
        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciaSesion.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        iniciaSesion.setForeground(new java.awt.Color(0, 0, 0));
        iniciaSesion.setText("INICIAR SESIÓN");
        panelInicio.add(iniciaSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 350, 50));

        frase_derecha.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        frase_derecha.setForeground(new java.awt.Color(0, 0, 0));
        frase_derecha.setText("Accede al sistema para realizar una renta");
        panelInicio.add(frase_derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 290, 40));

        frase1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        frase1.setForeground(new java.awt.Color(255, 255, 255));
        frase1.setText("Sistema de renta de vehiculos");
        panelInicio.add(frase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 50));

        bienvenido.setFont(new java.awt.Font("Yu Gothic UI", 0, 35)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenido.setText("Bienvenido a ");
        panelInicio.add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 220, 60));

        SIGERPRO.setFont(new java.awt.Font("Yu Gothic UI", 0, 70)); // NOI18N
        SIGERPRO.setForeground(new java.awt.Color(255, 255, 255));
        SIGERPRO.setText("RENTCAR");
        panelInicio.add(SIGERPRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 320, 100));

        jSeparator1.setBackground(new java.awt.Color(22, 163, 74));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);
        panelInicio.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 340, -1));

        jSeparator2.setBackground(new java.awt.Color(22, 163, 74));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOpaque(true);
        panelInicio.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 340, -1));

        fondoOscuro.setBackground(new java.awt.Color(17, 25, 54));
        fondoOscuro.setOpaque(true);
        panelInicio.add(fondoOscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 520));

        btnIniciar.setBackground(new java.awt.Color(37, 99, 235));
        btnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("INGRESAR");
        btnIniciar.setBorder(null);
        btnIniciar.setOpaque(true);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        panelInicio.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 220, 50));

        lblVer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVer1MouseClicked(evt);
            }
        });
        panelInicio.add(lblVer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 30, 30));

        lblVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerMouseClicked(evt);
            }
        });
        panelInicio.add(lblVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 30, 30));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(17, 24, 39));
        txtPassword.setText("Ingresa tu contraseña:");
        txtPassword.setBorder(null);
        txtPassword.setFocusable(false);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPasswordMouseEntered(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        panelInicio.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 340, 30));

        lblRecuperar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lblRecuperar.setForeground(new java.awt.Color(0, 0, 0));
        lblRecuperar.setText("¿Contraseña olvidada? Reestablecer ahora mismo");
        lblRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseExited(evt);
            }
        });
        panelInicio.add(lblRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 300, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(17, 24, 39));
        txtUsuario.setText("Ingrese su usuario o correo electrónico:");
        txtUsuario.setBorder(null);
        txtUsuario.setFocusable(false);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseExited(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        panelInicio.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 340, 30));

        fondoClaro.setBackground(new java.awt.Color(241, 245, 249));
        fondoClaro.setOpaque(true);
        panelInicio.add(fondoClaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 510, 537));

        getContentPane().add(panelInicio, "card20");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        String usuario = txtUsuario.getText().trim();
        String contrasena = new String(txtPassword.getPassword()).trim();

        if (usuario.isEmpty() || usuario.equals(textUser)) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa tu cédula.");
            return;
        }

        if (contrasena.isEmpty() || contrasena.equals(textPass)) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa tu contraseña.");
            return;
        }

        UsuarioJpaController usuarioController = new UsuarioJpaController();
        List<Usuario> usuarios = usuarioController.findUsuarioEntities();

        boolean loginExitoso = false;
        for (Usuario u : usuarios) {
            if (u.getCedula().equals(usuario) && u.getContrasena().equals(contrasena)) {
                loginExitoso = true;
                break;
            }
        }

        if (loginExitoso) {
            JOptionPane.showMessageDialog(this, "Login exitoso. Bienvenido!");
            // Abrir el panel principal
            new PanelPrincipal().setVisible(true);
            this.dispose(); // Cerrar la ventana de login
        } else {
            JOptionPane.showMessageDialog(this, "Cédula o contraseña incorrectos.");
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        txtPassword.requestFocusInWindow();
        txtPassword.setFocusable(true);
// TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        if (txtUsuario.getText().equals(textUser)) {
            txtUsuario.setText("");
        }
        txtUsuario.setText(txtUsuario.getText());
        comprobarP();


    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseEntered
        // TODO add your handling code here:
        txtUsuario.setFocusable(true);
    }//GEN-LAST:event_txtUsuarioMouseEntered

    private void txtUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseExited

// TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioMouseExited

    private void lblRecuperarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseEntered
        // TODO add your handling code here:
        lblRecuperar.setForeground(new Color(51, 102, 255));
    }//GEN-LAST:event_lblRecuperarMouseEntered

    private void lblRecuperarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseExited
        // TODO add your handling code here:
        lblRecuperar.setForeground(new Color(231, 143, 2));
    }//GEN-LAST:event_lblRecuperarMouseExited

    private void lblRecuperarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseClicked
     
    }//GEN-LAST:event_lblRecuperarMouseClicked

    


    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equals(textUser)) {
            txtUsuario.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().trim().isEmpty()) {
            txtUsuario.setText(textUser);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        btnIniciar.doClick();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        String texto = String.valueOf(txtPassword.getPassword());
        if (texto.equals(textPass)) {
            txtPassword.setText("");
            txtPassword.setEchoChar('●'); // Activa modo oculto
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        String texto = String.valueOf(txtPassword.getPassword());
        if (texto.trim().isEmpty()) {
            txtPassword.setText(textPass);
            txtPassword.setFont(new Font("Georgia", Font.PLAIN, 18));
            txtPassword.setEchoChar((char) 0); // Mostrar texto plano
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseEntered
        txtPassword.setFocusable(true);        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordMouseEntered

    private void lblVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerMouseClicked
        // TODO add your handling code here:
        lblVer1.setVisible(true);
        lblVer.setVisible(false);
        txtPassword.setEchoChar((char) 0);
        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lblVerMouseClicked

    private void lblVer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVer1MouseClicked
        // TODO add your handling code here:
        lblVer1.setVisible(false);
        lblVer.setVisible(true);
        txtPassword.setEchoChar('*');
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_lblVer1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    private void comprobarU() {
        if (txtUsuario.getText().trim().isEmpty()) {
            txtUsuario.setText(textUser);
        }
    }

    private void comprobarP() {
        if (txtPassword.getText().equals("")) {
            txtPassword.setText(textPass);
        }
        txtPassword.setText(txtPassword.getText());
    }

    private void ajustarImagenALabel(JLabel label, String rutaRelativa) {
        URL recurso = getClass().getResource("/" + rutaRelativa);

        if (recurso != null) {
            ImageIcon icono = new ImageIcon(recurso);
            Image imagenOriginal = icono.getImage();
            Image imagenEscalada = imagenOriginal.getScaledInstance(
                    label.getWidth(),
                    label.getHeight(),
                    Image.SCALE_SMOOTH
            );
            label.setIcon(new ImageIcon(imagenEscalada));
        } else {
            System.err.println("❌ No se encontró la imagen: /" + rutaRelativa);
        }
    }
 private void iniciarSesion() {
        if (txtUsuario.getText().isEmpty() || txtUsuario.getText().equals(textUser)) { // <--- MODIFICA ESTA LÍNEA
            JOptionPane.showMessageDialog(null, "Ingresa tu usuario o correo electrónico");
        } else if (txtPassword.getText().isEmpty() || txtPassword.getPassword().equals(textPass)) { // <--- MODIFICA ESTA LÍNEA
            JOptionPane.showMessageDialog(null, "Ingresa tu contraseña");
        } else {
            String usuario = txtUsuario.getText();
            String contra = txtPassword.getText(); // <--- MANTIENE ESTA LÍNEA (NO USAR getPassword())
//            listarUsuarios(usuario, contra);
        }
    }
// private void listarUsuarios(String user, String contra) {
//        ArrayList<Usuario> listaUsuario = controlU.listarUsuarios();
//
//        if (listaUsuario == null || listaUsuario.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "No se encontró ningún Usuario Registrado", "ERROR USUARIO", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        String status = verificarCredenciales(user, contra, listaUsuario);
//
//        switch (status) {
//            case "Acceso verificado":
//                JOptionPane.showMessageDialog(null, "Acceso verificado");
//                PanelPrincipal principal = new PanelPrincipal();
//                principal.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                principal.setVisible(true);
//                this.dispose(); // Close the login frame
//                break;
//            case "Usuario incorrecto":
//                JOptionPane.showMessageDialog(null, "Usuario incorrecto");
//                txtUsuario.setText(""); // Clear username field
//                comprobarU(); // Call your method to handle UI for incorrect username
//                break;
//            case "Contraseña incorrecta":
//                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
//                txtPassword.setText(""); // Clear password field
//                comprobarP(); // Call your method to handle UI for incorrect password
//                break;
//            default:
//                // This case should ideally not be reached
//                JOptionPane.showMessageDialog(null, "Error desconocido en la verificación de credenciales.");
//                break;
//        }
//    }
    public void ajustar() {


    }
    //Inicia sesion

    

    //Carga los archivos de la base de datos en un arrayList y luego comprueba
    

    //Inicia sesion
    

    //Carga los archivos de la base de datos en un arrayList y luego comprueba

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SIGERPRO;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel fondoClaro;
    private javax.swing.JLabel fondoOscuro;
    private javax.swing.JLabel frase1;
    private javax.swing.JLabel frase_derecha;
    private javax.swing.JLabel iniciaSesion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblRecuperar;
    private javax.swing.JLabel lblVer;
    private javax.swing.JLabel lblVer1;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
