/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author jc389
 */
public class PanelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
        jToolBar1.setFloatable(false);
      //  ajustarImagenALabel(LOGO, "Imagenes/logo.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuUsuarios = new javax.swing.JPopupMenu();
        menuGestionarU = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenuItem();
        menuVehiculos = new javax.swing.JPopupMenu();
        menuGestionarYate = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenuItem();
        menuCategorías = new javax.swing.JMenuItem();
        menuDisponibilidad = new javax.swing.JMenuItem();
        menuGestionarAuto = new javax.swing.JMenuItem();
        menuRentas = new javax.swing.JPopupMenu();
        menuCrearRenta = new javax.swing.JMenuItem();
        menuGestionarRentas = new javax.swing.JMenuItem();
        menuReservaciones = new javax.swing.JPopupMenu();
        menuCrearReservacion = new javax.swing.JMenuItem();
        menuGestionarReservaciones = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnRentas = new javax.swing.JButton();
        btnReservaciones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        menuUsuarios.setBackground(new java.awt.Color(153, 153, 255));

        menuGestionarU.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuGestionarU.setText("Gestionar Clientes");
        menuGestionarU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        menuGestionarU.setOpaque(true);
        menuGestionarU.setPreferredSize(new java.awt.Dimension(178, 22));
        menuGestionarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarUActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuGestionarU);

        menuHistorial.setBackground(new java.awt.Color(255, 255, 255));
        menuHistorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuHistorial.setText("Ver historial de clientes");
        menuHistorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuHistorial.setOpaque(true);
        menuHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistorialActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuHistorial);

        menuVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuGestionarYate.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarYate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuGestionarYate.setText("Gestionar Yates");
        menuGestionarYate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        menuGestionarYate.setOpaque(true);
        menuGestionarYate.setPreferredSize(new java.awt.Dimension(178, 22));
        menuGestionarYate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarYateActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuGestionarYate);

        menuMantenimiento.setBackground(new java.awt.Color(255, 255, 255));
        menuMantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuMantenimiento.setText("Mantenimiento");
        menuMantenimiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuMantenimiento.setOpaque(true);
        menuMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMantenimientoActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuMantenimiento);

        menuCategorías.setBackground(new java.awt.Color(255, 255, 255));
        menuCategorías.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCategorías.setText("Categorías");
        menuCategorías.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        menuCategorías.setOpaque(true);
        menuCategorías.setPreferredSize(new java.awt.Dimension(178, 22));
        menuCategorías.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoríasActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuCategorías);

        menuDisponibilidad.setBackground(new java.awt.Color(255, 255, 255));
        menuDisponibilidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuDisponibilidad.setText("Disponibilidad");
        menuDisponibilidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuDisponibilidad.setOpaque(true);
        menuDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDisponibilidadActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuDisponibilidad);

        menuGestionarAuto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuGestionarAuto.setText("Gestionar Autos");
        menuGestionarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarAutoActionPerformed(evt);
            }
        });
        menuVehiculos.add(menuGestionarAuto);

        menuRentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCrearRenta.setBackground(new java.awt.Color(255, 255, 255));
        menuCrearRenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCrearRenta.setText("Rentar un vehículo");
        menuCrearRenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuCrearRenta.setOpaque(true);
        menuCrearRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearRentaActionPerformed(evt);
            }
        });
        menuRentas.add(menuCrearRenta);

        menuGestionarRentas.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarRentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuGestionarRentas.setText("Gestionar rentas");
        menuGestionarRentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        menuGestionarRentas.setOpaque(true);
        menuGestionarRentas.setPreferredSize(new java.awt.Dimension(178, 22));
        menuGestionarRentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarRentasActionPerformed(evt);
            }
        });
        menuRentas.add(menuGestionarRentas);

        menuReservaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCrearReservacion.setBackground(new java.awt.Color(255, 255, 255));
        menuCrearReservacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCrearReservacion.setText("Reservar un vehículo");
        menuCrearReservacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuCrearReservacion.setOpaque(true);
        menuCrearReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearReservacionActionPerformed(evt);
            }
        });
        menuReservaciones.add(menuCrearReservacion);

        menuGestionarReservaciones.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarReservaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuGestionarReservaciones.setText("Gestionar reservaciones");
        menuGestionarReservaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        menuGestionarReservaciones.setOpaque(true);
        menuGestionarReservaciones.setPreferredSize(new java.awt.Dimension(178, 22));
        menuGestionarReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarReservacionesActionPerformed(evt);
            }
        });
        menuReservaciones.add(menuGestionarReservaciones);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(30, 58, 128));
        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(30, 58, 128));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inicio");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(true);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        btnUsuarios.setBackground(new java.awt.Color(30, 58, 128));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Clientes");
        btnUsuarios.setFocusable(false);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setOpaque(true);
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUsuarios);

        btnVehiculos.setBackground(new java.awt.Color(30, 58, 128));
        btnVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnVehiculos.setText("Vehiculos");
        btnVehiculos.setFocusable(false);
        btnVehiculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVehiculos.setOpaque(true);
        btnVehiculos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVehiculos);

        btnRentas.setBackground(new java.awt.Color(30, 58, 128));
        btnRentas.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRentas.setForeground(new java.awt.Color(255, 255, 255));
        btnRentas.setText("Rentas");
        btnRentas.setFocusable(false);
        btnRentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRentas.setOpaque(true);
        btnRentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRentas);

        btnReservaciones.setBackground(new java.awt.Color(30, 58, 128));
        btnReservaciones.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnReservaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnReservaciones.setText("Reservaciones");
        btnReservaciones.setFocusable(false);
        btnReservaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReservaciones.setOpaque(true);
        btnReservaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservacionesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReservaciones);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 70));

        jLabel2.setBackground(new java.awt.Color(30, 41, 59));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 41, 59));
        jLabel2.setText("Tu sistema de getión de renta de autos seguro y fácil de usar ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 270, 1010, 70));

        jLabel3.setBackground(new java.awt.Color(30, 41, 59));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 41, 59));
        jLabel3.setText("RentCAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 200, 260, 70));

        jLabel1.setBackground(new java.awt.Color(226, 232, 240));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1420, 770));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void ajustarImagenALabel(JLabel label, String rutaRelativa) {
        URL recurso = getClass().getResource("/" + rutaRelativa);

        if (recurso != null) {
            ImageIcon icono = new ImageIcon(recurso);
            Image imagenOriginal = icono.getImage();
            Image imagenEscalada = imagenOriginal.getScaledInstance(
                    label.getWidth(),
                    label.getHeight(),
                    Image.SCALE_SMOOTH
            );
            label.setIcon(new ImageIcon(imagenEscalada));
        } else {
            System.err.println("❌ No se encontró la imagen: /" + rutaRelativa);
        }
    }
    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
menuUsuarios.show(btnUsuarios, 0, btnUsuarios.getHeight());         // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void menuGestionarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarUActionPerformed
crudClientes cC= new crudClientes();
cC.setLocationRelativeTo(null);
cC.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_menuGestionarUActionPerformed

    private void menuHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHistorialActionPerformed

    private void menuGestionarYateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarYateActionPerformed
crudYate cY= new crudYate();
cY.setLocationRelativeTo(null);
cY.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_menuGestionarYateActionPerformed

    private void menuMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMantenimientoActionPerformed

    private void menuCategoríasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoríasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCategoríasActionPerformed

    private void menuDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDisponibilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDisponibilidadActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
menuVehiculos.show(btnVehiculos, 0, btnVehiculos.getHeight());          // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void menuGestionarRentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarRentasActionPerformed
        GestionRentas gR = new GestionRentas();
        gR.setLocationRelativeTo(null);
        gR.setVisible(true);
    }//GEN-LAST:event_menuGestionarRentasActionPerformed

    private void menuCrearRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearRentaActionPerformed
        GestionRentas gR = new GestionRentas();
        gR.setLocationRelativeTo(null);
        gR.setVisible(true);
    }//GEN-LAST:event_menuCrearRentaActionPerformed

    private void menuCrearReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearReservacionActionPerformed
        GestionReservaciones gRes = new GestionReservaciones();
        gRes.setLocationRelativeTo(null);
        gRes.setVisible(true);
    }//GEN-LAST:event_menuCrearReservacionActionPerformed

    private void menuGestionarReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarReservacionesActionPerformed
        GestionReservaciones gRes = new GestionReservaciones();
        gRes.setLocationRelativeTo(null);
        gRes.setVisible(true);
    }//GEN-LAST:event_menuGestionarReservacionesActionPerformed

    private void btnRentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentasActionPerformed
        menuRentas.show(btnRentas, 0, btnRentas.getHeight());
    }//GEN-LAST:event_btnRentasActionPerformed

    private void btnReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservacionesActionPerformed
        menuReservaciones.show(btnReservaciones, 0, btnReservaciones.getHeight());
    }//GEN-LAST:event_btnReservacionesActionPerformed

    private void menuGestionarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarAutoActionPerformed
        // TODO add your handling code here:
        AutoCombustion aC= new AutoCombustion();
aC.setLocationRelativeTo(null);
aC.setVisible(true);
    }//GEN-LAST:event_menuGestionarAutoActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRentas;
    private javax.swing.JButton btnReservaciones;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuCategorías;
    private javax.swing.JMenuItem menuCrearRenta;
    private javax.swing.JMenuItem menuCrearReservacion;
    private javax.swing.JMenuItem menuDisponibilidad;
    private javax.swing.JMenuItem menuGestionarAuto;
    private javax.swing.JMenuItem menuGestionarRentas;
    private javax.swing.JMenuItem menuGestionarReservaciones;
    private javax.swing.JMenuItem menuGestionarU;
    private javax.swing.JMenuItem menuGestionarYate;
    private javax.swing.JMenuItem menuHistorial;
    private javax.swing.JMenuItem menuMantenimiento;
    private javax.swing.JPopupMenu menuRentas;
    private javax.swing.JPopupMenu menuReservaciones;
    private javax.swing.JPopupMenu menuUsuarios;
    private javax.swing.JPopupMenu menuVehiculos;
    // End of variables declaration//GEN-END:variables
}
